In [24]:
import cobra
import pandas as pd
import json

In [26]:
# Load the model
model = cobra.io.read_sbml_model("/Users/helenscott/Documents/PhD/Segre-lab/GEM-repos/GEM-mit1002/model.xml")

In [4]:
# Load the ko results
ko_results = pd.read_csv("results/single_reaction_ko_results.csv", index_col=0)

In [5]:
ko_results

,glutamic acid,alanine,valine,aspartate,isoleucine,leucine,glycine,proline,cocktail
ids,,,,,,,,,
rxn00623_c0,0.000000e+00,4.826709e-32,0.000000e+00,0.000000e+00,-2.298357e-30,-3.028944e-32,2.279685e-31,1.513937e-30,0.000000e+00
rxn00640_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,5.738178e-01,7.022276e-01,6.477702e-01
rxn05369_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,5.738178e-01,7.022276e-01,6.477702e-01
EX_cpd00027_e0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,5.738178e-01,7.022276e-01,6.477702e-01
rxn00514_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,5.738178e-01,7.022276e-01,6.477702e-01
...,...,...,...,...,...,...,...,...,...
rxn08844_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,5.738178e-01,7.022276e-01,6.477702e-01
rxn08815_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,5.738178e-01,7.022276e-01,6.477702e-01
rxn05335_c0,3.259374e-16,1.680888e-19,2.273837e-16,3.515653e-17,-5.903659e-16,-4.336340e-16,2.153163e-16,1.106397e-15,-4.729264e-16
rxn03644_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,5.738178e-01,7.022276e-01,6.477702e-01
rxn05209_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,5.738178e-01,7.022276e-01,6.477702e-01

In [6]:
# Filter the data to only include reactions that are essential in at least one condition (growth rate < minimum growth rate threshold)
essential_reactions_df = ko_results[ko_results.lt(0.001).any(axis=1)]
essential_reactions_df

,glutamic acid,alanine,valine,aspartate,isoleucine,leucine,glycine,proline,cocktail
ids,,,,,,,,,
rxn00623_c0,0.000000e+00,4.826709e-32,0.000000e+00,0.000000e+00,-2.298357e-30,-3.028944e-32,2.279685e-31,1.513937e-30,0.000000e+00
rxn05465_c0,5.778308e-18,2.144925e-15,2.783241e-16,-4.660725e-17,-1.452808e-15,1.760932e-17,1.646642e-16,1.801786e-17,-4.569545e-17
rxn14334_c0,1.239027e-15,1.795412e-15,2.565756e-17,-4.536509e-17,-1.566202e-15,1.539032e-16,8.956719e-17,-4.985536e-16,4.117812e-15
rxn02835_c0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
rxn06723_c0,-3.749195e-16,1.536210e-15,-2.341248e-17,-3.720820e-16,1.172139e-15,3.495175e-16,1.689051e-15,9.137930e-16,1.927445e-17
...,...,...,...,...,...,...,...,...,...
rxn01106_c0,-1.185650e-14,3.222103e-14,3.410642e-14,-1.261406e-14,5.261953e-15,-4.492369e-14,1.865658e-14,1.002904e-13,-1.380937e-14
rxn02159_c0,4.804254e-16,8.717833e-16,1.715646e-16,3.555603e-16,-3.269012e-16,-8.435811e-16,-4.210996e-16,-5.705358e-16,9.493979e-17
rxn02201_c0,-2.636338e-16,-1.123213e-15,4.434753e-17,8.673187e-17,-1.434114e-16,-5.302349e-16,2.479883e-13,-1.302538e-15,-1.746098e-16
rxn15466_c0,-7.470210e-16,2.054098e-16,5.199776e-01,1.412314e-15,1.693953e-15,1.084846e-14,5.708084e-15,6.386815e-16,6.477702e-01
rxn05335_c0,3.259374e-16,1.680888e-19,2.273837e-16,3.515653e-17,-5.903659e-16,-4.336340e-16,2.153163e-16,1.106397e-15,-4.729264e-16

In [7]:
# Are there any reactions that are essential in only some conditions?
essential_in_less_than_all_conditions = essential_reactions_df[essential_reactions_df.gt(0.001).any(axis=1)]
essential_in_less_than_all_conditions

,glutamic acid,alanine,valine,aspartate,isoleucine,leucine,glycine,proline,cocktail
ids,,,,,,,,,
rxn03436_c0,2.378324e-16,1.267688e-15,2.087976e-16,-4.393353e-16,5.729583e-01,-1.317682e-15,-3.969609e-16,-1.620175e-16,0.647770
rxn03437_c0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.729583e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.647770
rxn00974_c0,7.055934e-01,5.366178e-01,4.883751e-01,5.782628e-01,5.380757e-01,3.246894e-14,5.545565e-01,7.005051e-01,0.643867
rxn09498_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,1.034952e-14,7.022276e-01,0.647770
rxn03435_c0,-3.143184e-16,-2.114378e-16,-7.756169e-16,-3.598169e-16,5.729583e-01,-1.397434e-16,-6.269780e-16,-9.290953e-16,0.647770
rxn01208_c0,-4.503614e-16,1.270719e-16,-4.675378e-16,1.530526e-16,5.675084e-18,4.992881e-01,-8.174125e-16,6.636869e-17,0.647770
rxn08043_c0,-7.071059e-16,3.158905e-16,-6.046440e-16,2.018137e-16,5.729583e-01,1.096573e-15,2.874232e-16,-7.605873e-16,0.647770
rxn00902_c0,-6.449227e-16,-3.706974e-16,7.525939e-16,2.445027e-17,-2.404315e-17,4.992881e-01,-1.081157e-15,-2.406588e-16,0.647770
rxn00336_c0,7.078060e-01,5.840358e-01,5.186927e-01,6.099625e-01,5.722736e-01,1.499593e-15,5.738178e-01,7.005051e-01,0.647770
rxn02789_c0,7.346976e-16,-8.312709e-19,-1.027734e-15,-7.913742e-16,1.236867e-16,4.992881e-01,6.935159e-16,-8.895992e-16,0.647770
rxn00692_c0,7.066062e-01,5.831839e-01,5.172411e-01,6.095220e-01,5.699570e-01,4.973346e-01,6.043216e-15,6.985589e-01,0.645217
rxn03062_c0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.992881e-01,0.000000e+00,0.000000e+00,0.647770
rxn01241_c0,5.743063e-01,4.544367e-01,-2.306702e-15,5.655849e-01,NaN,NaN,-8.453163e-16,5.653056e-01,0.482197
rxn00256_c0,7.055934e-01,5.366178e-01,4.883751e-01,5.782628e-01,5.380757e-01,-6.574402e-16,5.545565e-01,7.005051e-01,0.643867
rxn00737_c0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.729583e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.647770
rxn15021_c0,-5.279690e-16,-4.910428e-15,5.199776e-01,1.297719e-15,1.552804e-15,2.787779e-15,-5.003032e-16,-1.034821e-15,0.647770
rxn09499_c0,7.095282e-01,5.854568e-01,5.199776e-01,6.106959e-01,5.729583e-01,4.992881e-01,3.800808e-14,7.022276e-01,0.647770
rxn01388_c0,7.055934e-01,5.366178e-01,4.883751e-01,5.782628e-01,5.380757e-01,-2.677875e-15,5.545565e-01,7.005051e-01,0.643867
rxn15467_c0,-2.329830e-15,5.002980e-15,5.199776e-01,1.684946e-15,2.598392e-15,-1.015685e-14,4.556135e-15,-4.252055e-16,0.647770
rxn02811_c0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.992881e-01,0.000000e+00,0.000000e+00,0.647770
rxn09272_c0,-8.336606e-15,5.688206e-01,4.561876e-15,5.999475e-01,-5.205215e-15,5.441274e-16,5.738178e-01,-5.636237e-15,0.473257
rxn15466_c0,-7.470210e-16,2.054098e-16,5.199776e-01,1.412314e-15,1.693953e-15,1.084846e-14,5.708084e-15,6.386815e-16,0.647770

In [9]:
# Load my escher map json file
escher_map = json.load(open("/Users/helenscott/Documents/PhD/Segre-lab/GEM-repos/GEM-mit1002/escher/MIT1002_glycolysis-tca-etc_escher-map.json"))

In [16]:
# Get a list of all the reactions in the escher map
rxns_in_map = [escher_map[1]["reactions"][r]["bigg_id"] for r in escher_map[1]["reactions"]]

In [28]:
# What essential reactions are in the escher map?
essential_in_map = essential_reactions_df[essential_reactions_df.index.isin(rxns_in_map)].index
for rxn in essential_in_map:
    print(rxn , ": ", model.reactions.get_by_id(rxn).build_reaction_string(use_metabolite_names=True))

rxn00974_c0 :  Citrate <=> H2O + cis-Aconitate
EX_cpd00007_e0 :  O2 [e0] <=>
rxn00747_c0 :  Glyceraldehyde3-phosphate <=> Glycerone-phosphate
rxn00781_c0 :  NAD + Phosphate + Glyceraldehyde3-phosphate <=> NADH + H+ + 1,3-Bisphospho-D-glycerate
rxn00336_c0 :  Isocitrate --> Succinate + Glyoxalate
rxn00777_c0 :  ribose-5-phosphate <=> D-Ribulose5-phosphate
bio1_biomass :  53.633320980147 H2O + 53.633320980147 ATP + 0.00214538736074901 NAD + 0.00214538736074901 NADP + 0.00214538736074901 CoA + 0.00214538736074901 FAD + 0.00214538736074901 Pyridoxal phosphate + 0.00214538736074901 S-Adenosyl-L-methionine + 0.00214538736074901 Heme + 0.00214538736074901 Mn2+ + 0.00214538736074901 Zn2+ + 0.00214538736074901 GSH + 0.00214538736074901 Sulfate + 0.00214538736074901 TPP + 0.00214538736074901 Cu2+ + 0.00214538736074901 Ca2+ + 0.00214538736074901 Tetrahydrofolate + 0.00214538736074901 Cl- + 0.00214538736074901 Putrescine + 0.00214538736074901 Co2+ + 0.00214538736074901 10-Formyltetrahydrofolate + 0.00214538736074901 K+ + 0.00214538736074901 Riboflavin + 0.00214538736074901 Mg + 0.00214538736074901 Spermidine + 0.00214538736074901 5-Methyltetrahydrofolate + 0.00214538736074901 Siroheme + 0.0430129757525606 Bactoprenyl diphosphate + 0.0430129757525606 Lauroyl-KDO2-lipid IV(A) + 0.00214538736074901 Fe2+ + 0.00214538736074901 fe3 + 0.0163135131592289 DNA + 0.256322490462084 mRNA + 0.729636548111881 Protein + 0.033257289617049 phosphatidylethanolamine dioctadecanoyl + 0.033257289617049 1,2-dioctadecanoyl-sn-glycero-3-phosphoglycerol + 0.00214538736074901 Ubiquinone-8 --> 53.633320980147 ADP + 53.6311755927863 Phosphate + 53.633320980147 H+ + Biomass
rxn00786_c0 :  D-fructose-1,6-bisphosphate <=> Glycerone-phosphate + Glyceraldehyde3-phosphate
rxn01100_c0 :  ATP + 3-Phosphoglycerate <=> ADP + 1,3-Bisphospho-D-glycerate
rxn00459_c0 :  2-Phospho-D-glycerate <=> H2O + Phosphoenolpyruvate
rxn01241_c0 :  NAD + Protein N6-(dihydrolipoyl)lysine <=> NADH + H+ + Protein N6-(lipoyl)lysine [c0]
rxn00256_c0 :  H2O + Acetyl-CoA + Oxaloacetate --> CoA + H+ + Citrate
rxn00549_c0 :  H2O + D-fructose-1,6-bisphosphate --> Phosphate + D-fructose-6-phosphate
rxn01388_c0 :  Isocitrate <=> H2O + cis-Aconitate
rxn09272_c0 :  Succinate + Ubiquinone-8 --> Fumarate + Ubiquinol-8
rxn01106_c0 :  2-Phospho-D-glycerate <=> 3-Phosphoglycerate

In [29]:
# What essential reactions are NOT the escher map?
essential_not_in_map = essential_reactions_df[~essential_reactions_df.index.isin(rxns_in_map)].index
for rxn in essential_not_in_map:
    print(rxn , ": ", model.reactions.get_by_id(rxn).build_reaction_string(use_metabolite_names=True))

rxn00623_c0 :  3.0 NADPH + 3.0 H+ + Sulfite --> 3.0 H2O + 3.0 NADP + Bisulfide (HS-)
rxn05465_c0 :  Malonyl-CoA + ACP <=> CoA + Malonyl-ACP
rxn14334_c0 :  Isopentenyldiphosphate + ditrans,tricis-Hexaprenyl diphosphate --> PPi + H+ + ditrans,tetracis-Heptaprenyl diphosphate
rxn02835_c0 :  H2O + Phosphoribosyl-AMP <=> phosphoribosylformiminoaicar-phosphate
rxn06723_c0 :  UDP-3-O-(3-hydroxytetradecanoyl)-D-glucosamine + (3R)-3-Hydroxytetradecanoyl-ACP --> H+ + UDP-2,3-bis(3-hydroxytetradecanoyl)glucosamine + ACP
rxn03439_c0 :  CMP-KDO + KDO-lipid IV(A) <=> CMP + H+ + kdo2-lipid iva
rxn00791_c0 :  Anthranilate + PRPP --> PPi + H+ + N-5-phosphoribosyl-anthranilate
rxn00392_c0 :  ATP + Riboflavin <=> ADP + FMN + H+
rxn05114_c0 :  ATP + H2CO3 + AIR --> ADP + Phosphate + H+ + 5-phosphoribosyl-5-carboxyaminoimidazole
rxn05462_c0 :  (3R)-3-Hydroxyoctadecanoyl-ACP <=> H2O + (2E)-Octadecenoyl-ACP
rxn23042_c0 :  H+ + 4-Amino-2-methyl-5-diphosphomethylpyrimidine + 2-(2-Carboxy-4-methylthiazol-5-yl)ethyl phosphate --> CO2 + PPi + Thiamine phosphate
rxn43581_c0 :  H2O + 1-Hydroxy-2-methyl-2-butenyl 4-diphosphate + Oxidized flavodoxin <=> 2.0 H+ + 2-C-methyl-D-erythritol2-4-cyclodiphosphate + Reduced flavodoxin
rxn03175_c0 :  H+ + phosphoribosylformiminoaicar-phosphate <=> phosphoribulosylformimino-AICAR-phosphate
rxn05330_c0 :  (3R)-3-Hydroxyhexanoyl-ACP <=> H2O + (2E)-Hexenoyl-ACP
rxn01513_c0 :  ATP + H+ + dTMP <=> ADP + dTDP
rxn03910_c0 :  2-phospho-4--cytidine5-diphospho-2-C-methyl-D-erythritol <=> CMP + 2-C-methyl-D-erythritol2-4-cyclodiphosphate
rxn02474_c0 :  NADP + 5-Amino-6--5-phosphoribitylaminouracil <=> NADPH + H+ + 5-Amino-6--5-phosphoribosylaminouracil
rxn05342_c0 :  NADP + (3R)-3-Hydroxytetradecanoyl-ACP <=> NADPH + H+ + 3-Oxotetradecanoyl-ACP
rxn02507_c0 :  H+ + 1-(2-carboxyphenylamino)-1-deoxyribulose 5-phosphate --> H2O + CO2 + Indoleglycerol phosphate
rxn00832_c0 :  H2O + IMP <=> FAICAR
rxn05295_c0 :  0.524495708488791 ATP + 0.644609229516758 GTP + 0.400378403426558 CTP + 0.432408675700682 UTP --> 2.00189201713279 PPi + mRNA
rxn05323_c0 :  NADH + H+ + (2E)-Tetradecenoyl-ACP --> NAD + Tetradecanoyl-ACP
rxn01000_c0 :  H+ + Prephenate --> H2O + CO2 + Phenylpyruvate
rxn03393_c0 :  H+ + 3-Octaprenyl-4-hydroxybenzoate --> CO2 + 2-Octaprenylphenol
rxn01362_c0 :  PRPP + Orotate --> PPi + H+ + Orotidylic acid
DM_cpd11416_c0 :  Biomass -->
rxn03108_c0 :  ATP + H+ + 4-Amino-5-phosphomethyl-2-methylpyrimidine --> ADP + 4-Amino-2-methyl-5-diphosphomethylpyrimidine
rxn14061_c0 :  H+ + Isopentenyldiphosphate + trans,trans,cis-Geranylgeranyl diphosphate --> PPi + ditrans,dicis-Pentaprenyl diphosphate
rxn01256_c0 :  Chorismate --> Prephenate
rxn00907_c0 :  NADP + 5-10-Methylenetetrahydrofolate <=> NADPH + 5-10-Methenyltetrahydrofolate
EX_cpd00149_e0 :  Co2+ [e0] <=>
rxn08311_c0 :  CTP + 1,2-dioctadecanoyl-sn-glycerol 3-phosphate --> PPi + H+ + CDP-1,2-dioctadecanoylglycerol
rxn05327_c0 :  NADH + H+ + (2E)-Decenoyl-ACP --> NAD + Decanoyl-ACP
EX_cpd00099_e0 :  Cl- [e0] <=>
rxn05346_c0 :  H+ + Butyryl-ACP + Malonyl-ACP --> CO2 + 3-Oxohexanoyl-ACP + ACP
rxn03436_c0 :  2-Aceto-2-hydroxybutanoate <=> (R)-3-Hydroxy-3-methyl-2-oxopentanoate
rxn05350_c0 :  H+ + Hexanoyl-ACP + Malonyl-ACP --> CO2 + 3-Oxooctanoyl-ACP + ACP
rxn02475_c0 :  H2O + H+ + 2,5-Diamino-6-(5'-phosphoribosylamino)-4-pyrimidineone --> NH3 + 5-Amino-6--5-phosphoribosylaminouracil
rxn02774_c0 :  NAD + Precorrin 2 <=> NADH + 2.0 H+ + Sirohydrochlorin
rxn03437_c0 :  2,3-Dihydroxy-3-methylvalerate --> H2O + 3-methyl-2-oxopentoate
rxn00313_c0 :  H+ + meso-2,6-Diaminopimelate --> CO2 + L-Lysine
EX_cpd00063_e0 :  Ca2+ [e0] <=>
rxn01790_c0 :  NADP + Pantoate <=> NADPH + H+ + 2-Dehydropantoate
rxn02988_c0 :  Glycerone-phosphate + Iminoaspartate --> 2.0 H2O + Phosphate + Quinolinate
rxn08822_c0 :  H2O + 2-octadecanoyl-sn-glycerol 3-phosphate <=> 2.0 H+ + Glycerol-3-phosphate + Octadecanoate
EX_cpd00204_e0 :  CO [e0] -->
rxn00119_c0 :  ATP + H+ + UMP <=> ADP + UDP
EX_cpd10516_e0 :  fe3 [e0] <=>
rxn05460_c0 :  H+ + Hexadecanoyl-ACP + Malonyl-ACP --> CO2 + ACP + 3-Oxooctadecanoyl-ACP
rxn10480_c0 :  CO <=> CO [e0]
rxn03907_c0 :  CTP + 2-C-methyl-D-erythritol4-phosphate --> PPi + 4--cytidine5-diphospho-2-C-methyl-D-erythritol
rxn01213_c0 :  Isopentenyldiphosphate + DMAPP --> PPi + H+ + Geranyldiphosphate
rxn11663_c0 :  NAD + 4-(Phosphonooxy)-threonine --> NADH + CO2 + 3-Amino-2-oxopropyl phosphate
rxn01466_c0 :  Isopentenyldiphosphate + Geranyldiphosphate --> PPi + H+ + Farnesyldiphosphate
rxn43657_c0 :  Zn2+ [e0] + H+ [e0] --> Zn2+ + H+
rxn03445_c0 :  2-Oxoglutarate + 4-(Phosphonooxy)-threonine <=> L-Glutamate + 2-Oxo-3-hydroxy-4-phosphobutanoate
rxn09498_c0 :  Tetrahydrofolate + S-Aminomethyldihydrolipoamide --> NH3 + 5-10-Methylenetetrahydrofolate + Protein N6-(dihydrolipoyl)lysine
rxn09202_c0 :  2.0 H+ + phosphatidylserine dioctadecanoyl --> CO2 + phosphatidylethanolamine dioctadecanoyl
rxn05329_c0 :  (3R)-3-Hydroxybutanoyl-ACP <=> H2O + (2E)-Butenoyl-ACP
rxn02473_c0 :  D-erythro-imidazol-glycerol-phosphate --> H2O + imidazole acetol-phosphate
rxn02341_c0 :  H+ + (R)-4'-Phosphopantothenoyl-L-cysteine --> CO2 + Phosphopantetheine
rxn06937_c0 :  ATP + L-Glutamate + tRNA-Glu --> PPi + AMP + H+ + L-Glutamyl-tRNA-Glu
rxn15949_c0 :  H+ + Carboxyspermidine --> CO2 + Spermidine
rxn05328_c0 :  NADH + H+ + (2E)-Hexadecenoyl-ACP --> NAD + Hexadecanoyl-ACP
rxn02504_c0 :  Dihydroneopterin <=> Glycolaldehyde + 6-hydroxymethyl dihydropterin
rxn05322_c0 :  NADH + H+ + (2E)-Butenoyl-ACP --> NAD + Butyryl-ACP
rxn00438_c0 :  ATP + H+ + Thiamine phosphate --> ADP + TPP
rxn02213_c0 :  5-Dehydroquinate --> H2O + 3-Dehydroshikimate
rxn09210_c0 :  L-Serine + CDP-1,2-dioctadecanoylglycerol --> CMP + 2.0 H+ + phosphatidylserine dioctadecanoyl
rxn42709_c0 :  NADPH + S-Adenosyl-L-methionine + L-Tyrosine --> NADP + L-Methionine + H+ + p-Cresol + 5'-Deoxyadenosine + Iminoglycine
rxn00912_c0 :  H2O + 3-Methyl-2-oxobutanoate + 5-10-Methylenetetrahydrofolate <=> Tetrahydrofolate + 2-Dehydropantoate
rxn01117_c0 :  D-Arabinose5-phosphate <=> D-Ribulose5-phosphate
rxn02895_c0 :  ATP + Glycine + 5-Phosphoribosylamine --> ADP + Phosphate + H+ + GAR
rxn05326_c0 :  NADH + H+ + (2E)-Hexenoyl-ACP --> NAD + Hexanoyl-ACP
rxn03435_c0 :  NADP + 2,3-Dihydroxy-3-methylvalerate <=> NADPH + H+ + (R)-3-Hydroxy-3-methyl-2-oxopentanoate
rxn05333_c0 :  (3R)-3-Hydroxydecanoyl-ACP <=> H2O + (2E)-Decenoyl-ACP
rxn01208_c0 :  H+ + 2-isopropyl-3-oxosuccinate --> CO2 + 4-Methyl-2-oxopentanoate [c0]
rxn00686_c0 :  NADP + Tetrahydrofolate <=> NADPH + H+ + Dihydrofolate
rxn01019_c0 :  Ornithine + Carbamoylphosphate --> Phosphate + H+ + Citrulline
rxn08234_c0 :  Cl- [e0] <=> Cl-
rxn02476_c0 :  Phosphoenolpyruvate + 3-phosphoshikimate <=> Phosphate + 5-O--1-Carboxyvinyl-3-phosphoshikimate
rxn00863_c0 :  H2O + NAD + L-Histidinal --> NADH + 2.0 H+ + L-Histidine
rxn00209_c0 :  O2 + Pyridoxine phosphate --> Pyridoxal phosphate + H2O2
rxn02288_c0 :  4.0 H+ + UroporphyrinogenIII --> 4.0 CO2 + CoproporphyrinogenIII
fe3_reduction :  2.0 fe3 + Reducedferredoxin --> 2.0 Fe2+ + Oxidizedferredoxin
rxn02937_c0 :  ATP + 5'-Phosphoribosylformylglycinamidine --> ADP + Phosphate + H+ + AIR
rxn08043_c0 :  Pyruvate + H+ + 2-Oxobutyrate --> CO2 + 2-Aceto-2-hydroxybutanoate
EX_cpd00034_e0 :  Zn2+ [e0] <=>
rxn03397_c0 :  S-Adenosyl-L-methionine + 2-Octaprenyl-6-methoxy-1,4-benzoquinone --> S-Adenosyl-homocysteine + H+ + 2-Octaprenyl-3-methyl-6-methoxy-1,4-benzoquinone
rxn05294_c0 :  0.516637656497864 dATP + 0.516637656497864 dGTP + 0.516637656497864 dCTP + 0.516637656497864 TTP --> 2.06655062599146 PPi + DNA
rxn01519_c0 :  H2O + dUTP --> PPi + 2.0 H+ + dUMP
rxn03893_c0 :  4-Hydroxybenzoate + Farnesylfarnesylgeraniol --> PPi + H+ + 3-Octaprenyl-4-hydroxybenzoate
rxn00693_c0 :  Homocysteine + 5-Methyltetrahydrofolate <=> L-Methionine + Tetrahydrofolate
rxn00224_c0 :  Protoporphyrin + Fe2+ <=> Heme + 2.0 H+
rxn03958_c0 :  NADP + 2-C-methyl-D-erythritol4-phosphate <=> NADPH + H+ + 1-deoxy-D-xylulose5-phosphate
rxn03167_c0 :  3.0 H2O + 7,8-Dihydroneopterin 3'-triphosphate --> 3.0 Phosphate + 3.0 H+ + Dihydroneopterin
rxn00902_c0 :  H2O + Acetyl-CoA + 3-Methyl-2-oxobutanoate --> CoA + H+ + 2-Isopropylmalate
rxn05343_c0 :  H+ + Octanoyl-ACP + Malonyl-ACP --> CO2 + 3-Oxodecanoyl-ACP + ACP
rxn01512_c0 :  ATP + dTDP <=> ADP + TTP
cpd01042_transport :  p-Cresol --> p-Cresol [e0]
rxn05040_c0 :  D-Ribulose5-phosphate --> Formate + H+ + 3-4-dihydroxy-2-butanone4-phosphate
rxn05461_c0 :  NADPH + H+ + 3-Oxooctadecanoyl-ACP <=> NADP + (3R)-3-Hydroxyoctadecanoyl-ACP
rxn03909_c0 :  Pyruvate + H+ + Glyceraldehyde3-phosphate --> CO2 + 1-deoxy-D-xylulose5-phosphate
rxn00337_c0 :  ATP + L-Aspartate <=> ADP + 4-Phospho-L-aspartate
rxn02405_c0 :  CTP + KDO --> PPi + H+ + CMP-KDO
rxn06591_c0 :  NADPH + H+ + L-Glutamyl-tRNA-Glu --> NADP + L-Glutamate1-semialdehyde + tRNA-Glu
rxn01137_c0 :  H2O + H+ + Adenosine --> NH3 + Inosine
rxn03147_c0 :  ATP + L-Aspartate + 5'-Phosphoribosyl-4-carboxy-5-aminoimidazole --> ADP + Phosphate + H+ + SAICAR
rxn01520_c0 :  5-10-Methylenetetrahydrofolate + dUMP --> dTMP + Dihydrofolate
EX_cpd00254_e0 :  Mg [e0] <=>
rxn11946_c0 :  S-Adenosyl-L-methionine + 2-Octaprenyl-3-methyl-5-hydroxy-6-methoxy-1,4-benzoquinone <=> S-Adenosyl-homocysteine + H+ + Ubiquinone-8
rxn01973_c0 :  H2O + N-Succinyl-L-2,6-diaminopimelate <=> Succinate + LL-2,6-Diaminopimelate
rxn15947_c0 :  NADPH + H+ + Putrescine + L-Aspartate4-semialdehyde <=> H2O + NADP + Carboxyspermidine
rxn01257_c0 :  L-Glutamine + Chorismate <=> L-Glutamate + 4-amino-4-deoxychorismate
rxn03136_c0 :  SAICAR <=> H+ + Fumarate + AICAR
rxn12224_c0 :  O2 + 2-Octaprenyl-6-methoxyphenol --> H2O + 2-Octaprenyl-6-methoxy-1,4-benzoquinone
rxn00293_c0 :  UTP + N-Acetyl-D-glucosamine1-phosphate --> PPi + UDP-N-acetylglucosamine
rxn05616_c0 :  Mg <=> Mg [e0]
EX_cpd00009_e0 :  Phosphate [e0] <=>
rxn02789_c0 :  2-Isopropylmalate <=> H2O + 2-Isopropylmaleate
rxn06865_c0 :  kdo2-lipid iva + Dodecanoyl-ACP --> Lauroyl-KDO2-lipid IV(A) + ACP
rxn05618_c0 :  Mn2+ [e0] + H+ [e0] --> Mn2+ + H+
rxn39451_c0 :  NADH + H+ + (2S,4S)-4-Hydroxy-2,3,4,5-tetrahydrodipicolinate <=> H2O + NAD + tetrahydrodipicolinate
rxn05514_c0 :  Ca2+ + H+ [e0] <=> Ca2+ [e0] + H+
rxn00834_c0 :  H2O + NAD + IMP <=> NADH + H+ + XMP
rxn14333_c0 :  Isopentenyldiphosphate + ditrans,dicis-Pentaprenyl diphosphate --> PPi + H+ + ditrans,tricis-Hexaprenyl diphosphate
EX_cpd00048_e0 :  Sulfate [e0] <=>
rxn05340_c0 :  NADP + (3R)-3-Hydroxydodecanoyl-ACP <=> NADPH + H+ + 3-Oxododecanoyl-ACP
rxn00102_c0 :  H+ + H2CO3 <=> H2O + CO2
rxn01603_c0 :  ATP + L-Glutamate + Dihydropteroate --> ADP + Phosphate + H+ + Dihydrofolate
rxn01643_c0 :  NADPH + H+ + 4-Phospho-L-aspartate --> NADP + Phosphate + L-Aspartate4-semialdehyde
rxn03182_c0 :  CMP-KDO + Lipid IV(A) <=> CMP + H+ + KDO-lipid IV(A)
rxn00100_c0 :  ATP + Dephospho-CoA --> ADP + CoA + H+
rxn05006_c0 :  S-Adenosyl-L-methionine + Precorrin 1 <=> S-Adenosyl-homocysteine + Precorrin 2
rxn01739_c0 :  ATP + Shikimate --> ADP + H+ + 3-phosphoshikimate
rxn02508_c0 :  N-5-phosphoribosyl-anthranilate <=> 1-(2-carboxyphenylamino)-1-deoxyribulose 5-phosphate
rxn03080_c0 :  5-Amino-6-(1-D-ribitylamino)uracil + 3-4-dihydroxy-2-butanone4-phosphate --> 2.0 H2O + Phosphate + H+ + 6-7-Dimethyl-8--1-D-ribityllumazine
rxn00692_c0 :  H2O + Glycine + 5-10-Methylenetetrahydrofolate <=> L-Serine + Tetrahydrofolate
rxn03130_c0 :  H2O + UDP-2,3-bis(3-hydroxytetradecanoyl)glucosamine --> 2.0 H+ + UMP + Lipid X
rxn02939_c0 :  NAD + 4-Phosphoerythronate <=> NADH + H+ + 2-Oxo-3-hydroxy-4-phosphobutanoate
rxn03084_c0 :  H2O + ATP + L-Glutamine + N-Formyl-GAR --> ADP + Phosphate + L-Glutamate + H+ + 5'-Phosphoribosylformylglycinamidine
rxn01629_c0 :  5-Aminolevulinate <=> L-Glutamate1-semialdehyde
rxn01791_c0 :  ATP + beta-Alanine + Pantoate --> PPi + AMP + 2.0 H+ + PAN
rxn00338_c0 :  O2 + L-Aspartate --> H2O2 + H+ + Iminoaspartate
rxn02503_c0 :  ATP + 6-hydroxymethyl dihydropterin --> AMP + H+ + 2-Amino-4-hydroxy-6-hydroxymethyl-7-8-dihydropteridinediphosphate
rxn02320_c0 :  2-Oxoglutarate + L-histidinol-phosphate <=> L-Glutamate + imidazole acetol-phosphate
rxn00122_c0 :  ATP + FMN --> PPi + FAD
rxn00237_c0 :  ATP + GDP <=> ADP + GTP
rxn05195_c0 :  H2O + ATP + fe3 [e0] --> ADP + Phosphate + H+ + fe3
rxn08013_c0 :  H2O + 5'-Deoxyadenosine --> Adenine + 5'-deoxyribose
rxn00802_c0 :  L-Argininosuccinate <=> L-Arginine + Fumarate
rxn05468_c0 :  O2 [e0] --> O2
rxn03843_c0 :  Isopentenyldiphosphate + Farnesyldiphosphate --> PPi + H+ + trans,trans,cis-Geranylgeranyl diphosphate
rxn05341_c0 :  NADP + (3R)-3-Hydroxyoctanoyl-ACP <=> NADPH + H+ + 3-Oxooctanoyl-ACP
rxn00048_c0 :  H+ + 2.0 6-7-Dimethyl-8--1-D-ribityllumazine --> Riboflavin + 5-Amino-6-(1-D-ribitylamino)uracil
rxn02304_c0 :  3.0 O2 + 2.0 ProtoporphyrinogenIX --> 6.0 H2O + 2.0 Protoporphyrin
rxn14011_c0 :  Isopentenyldiphosphate + ditrans,pentacis-Octaprenyl diphosphate --> PPi + H+ + ditrans,hexacis-Nonaprenyl diphosphate
rxn02175_c0 :  ATP + Phosphopantetheine --> PPi + Dephospho-CoA
rxn00770_c0 :  ATP + ribose-5-phosphate <=> AMP + H+ + PRPP
rxn05348_c0 :  H+ + Decanoyl-ACP + Malonyl-ACP --> CO2 + 3-Oxododecanoyl-ACP + ACP
rxn03908_c0 :  ATP + 4--cytidine5-diphospho-2-C-methyl-D-erythritol --> ADP + H+ + 2-phospho-4--cytidine5-diphospho-2-C-methyl-D-erythritol
rxn02834_c0 :  H2O + Phosphoribosyl-ATP --> PPi + 2.0 H+ + Phosphoribosyl-AMP
rxn09128_c0 :  H2O + 1,2-dioctadecanoyl-sn-glycerol 3-phosphate <=> H+ + Octadecanoate + 2-octadecanoyl-sn-glycerol 3-phosphate
cpd15380_transport :  5'-deoxyribose <=> 5'-deoxyribose [e0]
rxn03159_c0 :  UDP-2,3-bis(3-hydroxytetradecanoyl)glucosamine + Lipid X <=> UDP + Lipid A disaccharide
rxn19704_c0 :  NADP + H+ + Reduced flavodoxin <=> NADPH + Oxidized flavodoxin
rxn06076_c0 :  CDP + Reduced thioredoxin --> H2O + dCDP + Oxidized thioredoxin
rxn12510_c0 :  ATP + PAN --> ADP + H+ + 4-phosphopantothenate
rxn16823_c0 :  2-[(2R,5Z)-2-Carboxy-4-methylthiazol-5(2H)-ylidene]ethyl phosphate --> 2-(2-Carboxy-4-methylthiazol-5-yl)ethyl phosphate
rxn02264_c0 :  Hydroxymethylbilane <=> H2O + UroporphyrinogenIII
rxn05030_c0 :  Isopentenyldiphosphate + all trans Decaprenyl diphosphate --> PPi + H+ + Bactoprenyl diphosphate
rxn05339_c0 :  NADP + (3R)-3-Hydroxybutanoyl-ACP <=> NADPH + H+ + Acetoacetyl-ACP
EX_cpd00205_e0 :  K+ [e0] <=>
rxn05324_c0 :  NADH + H+ + (2E)-Dodecenoyl-ACP --> NAD + Dodecanoyl-ACP
rxn01740_c0 :  NADP + Shikimate <=> NADPH + H+ + 3-Dehydroshikimate
rxn03087_c0 :  L-Glutamate + N-Succinyl-L-2-amino-6-oxopimelate <=> 2-Oxoglutarate + N-Succinyl-L-2,6-diaminopimelate
rxn00126_c0 :  H2O + ATP + L-Methionine --> Phosphate + PPi + S-Adenosyl-L-methionine + H+
EX_cpd00030_e0 :  Mn2+ [e0] <=>
rxn03062_c0 :  NAD + 3-Isopropylmalate <=> NADH + H+ + 2-isopropyl-3-oxosuccinate
rxn05338_c0 :  NADP + (3R)-3-Hydroxydecanoyl-ACP <=> NADPH + H+ + 3-Oxodecanoyl-ACP
rxn03394_c0 :  NADPH + O2 + H+ + 2-Octaprenylphenol --> H2O + NADP + 2-Octaprenyl-6-hydroxyphenol
rxn02404_c0 :  H2O + 3-Deoxy-D-manno-octulosonate8-phosphate --> Phosphate + KDO
rxn09113_c0 :  Glycerol-3-phosphate + CDP-1,2-dioctadecanoylglycerol <=> CMP + Phosphatidylglycerophosphate dioctadecanoyl
rxn00141_c0 :  H2O + S-Adenosyl-homocysteine --> Homocysteine + Adenosine
rxn00029_c0 :  2.0 5-Aminolevulinate --> 2.0 H2O + H+ + Porphobilinogen
rxn05344_c0 :  H+ + Tetradecanoyl-ACP + Malonyl-ACP --> CO2 + 3-Oxohexadecanoyl-ACP + ACP
EX_cpd01042_e0 :  p-Cresol [e0] -->
rxn01974_c0 :  LL-2,6-Diaminopimelate <=> meso-2,6-Diaminopimelate
rxn00493_c0 :  2-Oxoglutarate + L-Phenylalanine <=> L-Glutamate + Phenylpyruvate
rxn05325_c0 :  NADH + H+ + (2E)-Octenoyl-ACP --> NAD + Octanoyl-ACP
rxn00555_c0 :  L-Glutamine + D-fructose-6-phosphate <=> L-Glutamate + D-Glucosamine phosphate
rxn08801_c0 :  H2O + 1-octadecanoyl-sn-glycerol 3-phosphate <=> H+ + Glycerol-3-phosphate + Octadecanoate
rxn05289_c0 :  NADP + Reduced thioredoxin <=> NADPH + H+ + Oxidized thioredoxin
rxn03031_c0 :  H2O + Succinyl-CoA + tetrahydrodipicolinate --> CoA + N-Succinyl-L-2-amino-6-oxopimelate
rxn00117_c0 :  ATP + UDP <=> ADP + UTP
rxn05336_c0 :  NADP + (3R)-3-Hydroxyhexadecanoyl-ACP <=> NADPH + H+ + 3-Oxohexadecanoyl-ACP
EX_cpd15380_e0 :  5'-deoxyribose [e0] -->
rxn01332_c0 :  H2O + Phosphoenolpyruvate + D-Erythrose4-phosphate --> Phosphate + DAHP
rxn00060_c0 :  H2O + 4.0 Porphobilinogen --> 4.0 NH3 + Hydroxymethylbilane
EX_cpd00058_e0 :  Cu2+ [e0] <=>
rxn00737_c0 :  L-Threonine --> NH3 + 2-Oxobutyrate
rxn00710_c0 :  H+ + Orotidylic acid --> CO2 + UMP
rxn20643_c0 :  S-Adenosyl-L-methionine + AIR --> Formate + L-Methionine + 2.0 H+ + CO + 4-Amino-5-phosphomethyl-2-methylpyrimidine + 5'-Deoxyadenosine
rxn05296_c0 :  27.684983832597 H2O + 35.5949792133389 ATP + 0.388588889398408 L-Glutamate + 0.904337964148734 Glycine + 0.759012038032257 L-Alanine + 0.506271296960121 L-Lysine + 0.356206481948541 L-Aspartate + 0.437557407981134 L-Arginine + 0.388588889398408 L-Glutamine + 0.31829537078772 L-Serine + 0.226676852149071 L-Methionine + 0.0837203704801448 L-Tryptophan + 0.274065741100097 L-Phenylalanine + 0.214039815095465 L-Tyrosine + 0.135058333510422 L-Cysteine + 0.665813889761907 L-Leucine + 0.140587037221375 L-Histidine + 0.326983333762075 L-Proline + 0.356206481948541 L-Asparagine + 0.624743519337685 L-Valine + 0.3743722227131 L-Threonine + 0.42886944500678 L-Isoleucine --> 35.5949792133389 ADP + 35.5949792133389 Phosphate + 35.5949792133389 H+ + Protein
rxn00416_c0 :  H2O + ATP + L-Aspartate + L-Glutamine --> PPi + AMP + L-Glutamate + 2.0 H+ + L-Asparagine
rxn09037_c0 :  5.0 Isopentenyldiphosphate + Farnesyldiphosphate --> 5.0 PPi + 5.0 H+ + Farnesylfarnesylgeraniol
rxn08239_c0 :  H2O + ATP + Co2+ [e0] --> ADP + Phosphate + H+ + Co2+
rxn01331_c0 :  H2O + NAD + D-Erythrose4-phosphate --> NADH + 2.0 H+ + 4-Phosphoerythronate
rxn40037_c0 :  Pyruvate + L-Aspartate4-semialdehyde --> H2O + H+ + (2S,4S)-4-Hydroxy-2,3,4,5-tetrahydrodipicolinate
rxn03395_c0 :  S-Adenosyl-L-methionine + 2-Octaprenyl-6-hydroxyphenol <=> S-Adenosyl-homocysteine + H+ + 2-Octaprenyl-6-methoxyphenol
rxn13957_c0 :  Isopentenyldiphosphate + ditrans,hexacis-Nonaprenyl diphosphate --> PPi + 3.0 H+ + all trans Decaprenyl diphosphate
rxn00789_c0 :  ATP + PRPP --> PPi + H+ + Phosphoribosyl-ATP
rxn05345_c0 :  H+ + Dodecanoyl-ACP + Malonyl-ACP --> CO2 + 3-Oxotetradecanoyl-ACP + ACP
rxn02331_c0 :  H2O + Phosphoenolpyruvate + D-Arabinose5-phosphate --> Phosphate + 3-Deoxy-D-manno-octulosonate8-phosphate
rxn03181_c0 :  ATP + Lipid A disaccharide --> ADP + H+ + Lipid IV(A)
rxn05005_c0 :  S-Adenosyl-L-methionine + UroporphyrinogenIII <=> S-Adenosyl-homocysteine + H+ + Precorrin 1
thiazol_synth :  ATP + L-Cysteine + 1-deoxy-D-xylulose5-phosphate + Reducedferredoxin + Iminoglycine --> 2.0 H2O + PPi + AMP + L-Alanine + Oxidizedferredoxin + 2-[(2R,5Z)-2-Carboxy-4-methylthiazol-5(2H)-ylidene]ethyl phosphate
rxn01465_c0 :  H2O + S-Dihydroorotate <=> H+ + N-Carbamoyl-L-aspartate
rxn01434_c0 :  ATP + L-Aspartate + Citrulline --> PPi + AMP + 2.0 H+ + L-Argininosuccinate
rxn05332_c0 :  (3R)-3-Hydroxyhexadecanoyl-ACP <=> H2O + (2E)-Hexadecenoyl-ACP
rxn02212_c0 :  DAHP --> Phosphate + 5-Dehydroquinate
rxn05464_c0 :  NADH + H+ + (2E)-Octadecenoyl-ACP --> NAD + Octadecanoyl-ACP
rxn15021_c0 :  2.0 Pyruvate + H+ --> CO2 + (S)-2-Acetolactate
rxn05212_c0 :  Cu2+ [e0] --> Cu2+
rxn00966_c0 :  Chorismate --> Pyruvate + 4-Hydroxybenzoate
rxn09106_c0 :  H2O + Phosphatidylglycerophosphate dioctadecanoyl --> Phosphate + H+ + 1,2-dioctadecanoyl-sn-glycero-3-phosphoglycerol
rxn14040_c0 :  Isopentenyldiphosphate + ditrans,tetracis-Heptaprenyl diphosphate --> PPi + H+ + ditrans,pentacis-Octaprenyl diphosphate
rxn06729_c0 :  UDP-N-acetylglucosamine + (3R)-3-Hydroxytetradecanoyl-ACP --> UDP-3-O-(3-hydroxytetradecanoyl)-N-acetylglucosamine + ACP
rxn09499_c0 :  Glycine + H+ + Protein N6-(lipoyl)lysine [c0] --> CO2 + S-Aminomethyldihydrolipoamide

In [30]:
# Add a reaction name column to the essential reactions dataframe
essential_reactions_df["reaction_name"] = essential_reactions_df.index.map(lambda x: model.reactions.get_by_id(x).name)
# Add a reaction string column to the essential reactions dataframe
essential_reactions_df["reaction_string"] = essential_reactions_df.index.map(lambda x: model.reactions.get_by_id(x).build_reaction_string(use_metabolite_names=True))
# Save
essential_reactions_df.to_csv("results/essential_reactions_with_names_and_strings.csv")

/var/folders/sg/v4dtbt1502lfm_z5_nvpyv0h0000gn/T/ipykernel_87583/970201374.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  essential_reactions_df["reaction_name"] = essential_reactions_df.index.map(lambda x: model.reactions.get_by_id(x).name)
/var/folders/sg/v4dtbt1502lfm_z5_nvpyv0h0000gn/T/ipykernel_87583/970201374.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  essential_reactions_df["reaction_string"] = essential_reactions_df.index.map(lambda x: model.reactions.get_by_id(x).build_reaction_string(use_metabolite_names=True))